### ISSUE TITLE
Why yet-another-CLI-framework™?

### ISSUE THREAD

**Issue by Wulfheart** [leaanthony/clir#5]
Hey,

your package looks promising in my eyes, I especially like the logo. However it is not clear to me, what the benefits of this yet-another-CLI-framework™ in comparsion to other cli-frameworks like commandeer or cobra are. Could you explain them a little bit?

**Comment by tmclane** [comment]
Have you tried it?  It's much simpler to get something setup compared to cobra.  I don't know anything about commandeer.

I personally would recommend you evaluate all the options and decide which works best for you.  Heck if it is none of them you could always write your own library.

**Comment by leaanthony** [comment]
Agree with Travis. Only you can decide if something is good for you or not.
The reason I wrote it was for simplicity and clarity.

I guess at the end of the day, it's simple and it works.
