### ISSUE TITLE
Splitting commands in different files

### ISSUE THREAD

**Issue by Wulfheart** [leaanthony/clir#8]
Hello,

does clir support it to make for each command one file or do I have to write my own little hack?

**Comment by tmclane** [comment]
The way I did it was place each command in it's own file in a `cmd` package with the code which instantiates and adds each `command` to the `init` function:

```
func init() {
	run := cli.NewSubCommand("run", "Starts the program")
	run.Action(func() error {
		p := &program.Program{}
		return p.Run()
	})
	silent := run.NewSubCommand("silent", "Disables console logging")
	silent.Action(func() error {
		fmt.Printf("Silent running..")
		return nil
	})
}
```

**Comment by Wulfheart** [comment]
Thanks. Helped me.
